---

- name: Query VPCs {{ item.vpc1 }}
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:name": "{{ item.vpc1 }}"
  register: vpc1

- name: Query VPCs {{ item.vpc2 }}
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:name": "{{ item.vpc2 }}"
  register: vpc2

- name: List all VPC peers
  community.aws.ec2_vpc_peering_info:
    region: "{{ vpcs['vpc1'].ec2_vpc_region }}"
  register: all_vpc_peers

- name: Delete vpc1 peering connection
  community.aws.ec2_vpc_peer:
    region: "{{ vpcs['vpc1'].ec2_vpc_region }}"
    peering_id: "{{ vpc1.vpc_peering_connection_id }}"
    state: absent
  loop: "{{ all_vpc_peers.vpc_peering_connections }}"

- name: Wait VPC peering connection to be deleted
  ansible.builtin.pause:
    seconds: 5

- name: Loop for VPCs deletion
  include_tasks: main_loop_vpcs.yml
  loop: "{{ vpcs }}"
