---

- name: Query VPCs
  amazon.aws.ec2_vpc_net_info:
    region: "{{ ec2_vpc_region_1 }}"
    filters:
      "tag:name": "{{ ec2_vpc_name_1 }}"
  register: vpc_1

- name: Query Subnets
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ ec2_vpc_region_1 }}"
    filters:
      "tag:name": "{{ ec2_subnet_name_1 }}"
  register: subnet_1

- name: Query Route Tables
  amazon.aws.ec2_vpc_route_table_info:
    region: "{{ ec2_vpc_region_1 }}"
    filters:
      "tag:name": "{{ ec2_rt_name_1 }}"
  register: rtb_1

- name: Terminate RHEL instance
  amazon.aws.ec2_instance:
    state: absent
    region: "{{ ec2_vpc_region_1 }}"
    filters:
      "tag:name": "{{ ec2_instance_name_1 }}"

- name: Delete Security Group
  amazon.aws.ec2_group:
    name: "{{ ec2_sg_name_1 }}"
    region: "{{ ec2_vpc_region_1 }}"
    state: absent

- name: Delete Subnet in VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_1.vpcs[0].id }}"
    cidr: "{{ subnet_1.subnets[0].cidr_block }}"
    region: "{{ ec2_vpc_region_1 }}"
    state: absent
  when: vpc_1.vpcs | length > 0 and subnet_1.subnets | length > 0

- name: Delete Route Table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc_1.vpcs[0].id }}"
    region: "{{ ec2_vpc_region_1 }}"
    route_table_id: "{{ rtb_1.route_tables[0].id }}"
    lookup: id
    state: absent
  when: vpc_1.vpcs | length > 0 and rtb_1.route_tables | length > 0

- name: Delete Internet Gateway (IGW)
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc_1.vpcs[0].id }}"
    region: "{{ ec2_vpc_region_1 }}"
    state: absent
  when: vpc_1.vpcs | length > 0

- name: Delete VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ ec2_vpc_name_1 }}"
    region: "{{ ec2_vpc_region_1 }}"
    cidr_block: "{{ vpc_1.vpcs[0].cidr_block }}"
    state: absent
  when: vpc_1.vpcs | length > 0

