---

- name: Loop for VPCs deletion
  include_tasks: main_loop_vpcs.yml
  loop: "{{ vpcs }}"

- name: Query VPCs {{ vpcs[0].ec2_vpc_name }}
  amazon.aws.ec2_vpc_net_info:
    region: "{{ vpcs[0].ec2_vpc_region }}"
    filters:
      "tag:name": "{{ vpcs[0].ec2_vpc_name }}"
  register: vpc1

- name: Query VPCs {{ vpcs[1].ec2_vpc_name }}
  amazon.aws.ec2_vpc_net_info:
    region: "{{ vpcs[1].ec2_vpc_region }}"
    filters:
      "tag:name": "{{ vpcs[1].ec2_vpc_name }}"
  register: vpc2

- name: Delete a VPC peering connection
  community.aws.ec2_vpc_peer:
    region: "{{ vpcs[0].ec2_vpc_region }}"
    #peering_id: "{{ manage_vpc_peering_vpc_peering_conn_id }}"
    state: absent

- name: Wait for VPC peering connection to be deleted
  ansible.builtin.pause:
    seconds: 5