---

- name: List all VPC peers
  community.aws.ec2_vpc_peering_info:
    region: "{{ vpcs[0].ec2_vpc_region }}"
  register: all_vpc_peers

- name: Delete all VPC peering connections
  community.aws.ec2_vpc_peer:
    region: "{{ vpcs[0].ec2_vpc_region }}"
    peering_id: "{{ item.vpc_peering_connection_id }}"
    state: absent
  loop: "{{ all_vpc_peers.vpc_peering_connections }}"

- name: Wait VPC peering connection to be deleted
  ansible.builtin.pause:
    seconds: 5

- name: Loop for VPCs deletion
  include_tasks: main_loop_vpcs.yml
  loop: "{{ vpcs }}"
