---

- name: Query VPCs {{ item.vpc }}
  amazon.aws.ec2_vpc_net_info:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    filters:
      "tag:name": "{{ item.vpc }}"
  register: vpc

- name: Query VPCs {{ item.peer_vpc }}
  amazon.aws.ec2_vpc_net_info:
    region: "{{ vpcs[item.peer_vpc].ec2_vpc_region }}"
    filters:
      "tag:name": "{{ item.peer_vpc }}"
  register: peer_vpc

- name: List all VPC peers
  community.aws.ec2_vpc_peering_info:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
  register: all_vpc_peers

- name: Delete peering connection
  community.aws.ec2_vpc_peer:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    peering_id: "{{ vpc.vpc_peering_connection_id }}"
    state: absent
  loop: "{{ all_vpc_peers.vpc_peering_connections }}"

- name: Wait VPC peering connection to be deleted
  ansible.builtin.pause:
    seconds: 5

- name: Loop for VPCs deletion
  include_tasks: main_loop_vpcs.yml
  loop: "{{ vpcs }}"
