---

- name: Query Subnets {{ item.subnet }}
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ item.subnet }}"
  register: subnet

- name: Create Transit VPC attachment {{ item.vpc }}
  community.aws.ec2_transit_gateway_vpc_attachment:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    name: "{{ item.vpc }}"
    transit_gateway: "{{ transit.transit_gateway.transit_gateway_id }}"
    subnets: "{{ subnet.subnets[0].subnet_id }}"
    tags:
      Name: "{{ item.vpc }}"
    purge_subnets: false
    state: present
  register: transit_attachment

- name: Transit Gateway attachment route table update
  include_tasks: main_loop_routes.yml
  loop: "{{ item.routes }}"
