---

- name: Loop for VPCs creation
  include_tasks: main_loop_vpcs.yml
  loop: "{{ vpcs | dict2items }}"

- name: Transit Gateway creation
  include_tasks: main_loop_transit.yml
  loop: "{{ transits | dict2items }}"
