---

- name: Create transit gateway "{{ item.name }}"
  community.aws.ec2_transit_gateway:
    region: "{{ item.region }}"
    asn: "{{ item.asn }}"
    auto_associate: true
    auto_propagate: true
    tags:
      Name: "{{ item.name }}"
    description: "Transit Gateway {{ item.name }}"
    state: present
  register: transit

- name: Verify transit gateway was created
  ansible.builtin.debug:
    msg: Transit Gateway successfully created/updated.
  when: transit.changed

- name: Debug transit gateway
  ansible.builtin.debug:
    msg: "Transit Gateway {{ transit.transit_gateway.transit_gateway_id }}"

- name: Transit Gateway attachments creation
  include_tasks: main_loop_attachments.yml
  loop: "{{ item.attachments }}"
