---

- name: Update Route Table with Transit Routes {{ transit_attachment.attachments[0].vpc_id }} -> {{ item.vpc }}
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ transit_attachment.attachments[0].vpc_id }}"
    region: "{{ vpcs[transit_attachment.attachments[0].tags.Name].ec2_vpc_region }}"
    purge_subnets: no
    purge_routes: no
    tags:
      Name: "{{ vpcs[transit_attachment.attachments[0].tags.Name].ec2_rt_name }}"
    routes:
      - dest: "{{ vpcs[item.vpc].ec2_subnet_cidr }}"
        gateway_id: "{{ transit.transit_gateway.transit_gateway_id }}"
    state: present
