---

- name: Create transit gateway "{{ item.name }}"
  community.aws.ec2_transit_gateway:
    asn: "{{ item.asn }}"
    tags: "{{ item.name }}"
    description: "Transit Gateway {{ item.name }}"
    state: present
  register: transit

- name: Verify transit gateway was created
  ansible.builtin.debug:
    msg: Transit Gateway successfully created/updated.
  when: transit.changed

- name: Debug transit
  ansible.builtin.debug:
    msg: "Transit Gateway {{ transit.transit_gateway.transit_gateway_id }}"

- name: Print debug msg
  ansible.builtin.debug:
    msg: Transit Gateway '{{ manage_transit_gateway_tgw_result.transit_gateway.transit_gateway_id }}' exists, no updates needed.
  when: not manage_transit_gateway_tgw_result.changed

- name: Transit Gateway attachment creation
  include_tasks: main_loop_attachments.yml
  loop: "{{ item.attachments }}"
