---

- name: Query VPC {{ item.vpc }}
  amazon.aws.ec2_vpc_net_info:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ item.vpc }}"
  register: vpc

- name: Update Route Table with Transit Routes {{ item.route }}
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    region: "{{ vpcs[item.peer_vpc].ec2_vpc_region }}"
    purge_routes: no
    tags:
      Name: "{{ vpcs[item.peer_vpc].ec2_rt_name }}"
    routes:
      - dest: "{{ vpcs[item.vpc].ec2_subnet_cidr }}"
        gateway_id: "{{ transit.transit_gateway.transit_gateway_id }}"
    state: present
