---

- name: Query VPC {{ item.vpc }}
  amazon.aws.ec2_vpc_net_info:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    filters:
      "tag:name": "{{ item.vpc }}"
  register: vpc

- name: Query VPC {{ item.peer_vpc }}
  amazon.aws.ec2_vpc_net_info:
    region: "{{ vpcs[item.peer_vpc].ec2_vpc_region }}"
    filters:
      "tag:name": "{{ item.peer_vpc }}"
  register: peer_vpc

- name: Create VPC peering request
  community.aws.ec2_vpc_peer:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    peer_region: "{{ vpcs[item.peer_vpc].ec2_vpc_region }}"
    vpc_id: "{{ vpc.vpcs[0].id }}"
    peer_vpc_id: "{{ peer_vpc.vpcs[0].id }}"
    state: present
  register: vpc_peering_request

- name: Ensure VPC peering connection request
  community.aws.ec2_vpc_peering_info:
    peer_connection_ids:
      - "{{ vpc_peering_request.peering_id }}"
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
  register: peering_info
  retries: 3
  delay: 5
  until: peering_info.vpc_peering_connections[0].vpc_peering_connection_id is defined

- name: Wait for peering request to be created
  ansible.builtin.pause:
    seconds: 5

- name: Accept VPC peering request
  community.aws.ec2_vpc_peer:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    peering_id: "{{ vpc_peering_request.peering_id }}"
    state: accept
  register: vpc_peering_accept


- name: Get Routing Table Info {{ vpcs[item.vpc].ec2_rt_name }}
  amazon.aws.ec2_vpc_route_table_info:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ vpcs[item.vpc].ec2_rt_name }}"
      "tag:name": "{{ vpcs[item.vpc].ec2_rt_name }}"
  register: vpc_rt

- name: Get Routing Table Info {{ vpcs[item.peer_vpc].ec2_rt_name }}
  amazon.aws.ec2_vpc_route_table_info:
    region: "{{ vpcs[item.peer_vpc].ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ vpcs[item.peer_vpc].ec2_rt_name }}"
      "tag:name": "{{ vpcs[item.peer_vpc].ec2_rt_name }}"
  register: peer_vpc_rt

# - name: Update Route Table {{ vpcs[item.vpc].ec2_rt_name }} and IGW route 
#   amazon.aws.ec2_vpc_route_table:
#     vpc_id: "{{ vpc.vpcs[0].id }}"
#     region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
#     state: present
#     route_table_id
#     routes:
#       - dest: "{{ vpcs[item.peer_vpc].ec2_subnet_cidr  }}"
#         vpc_peering_connection_id: "{{ vpc_peering_request.peering_id }}"