---

- name: Loop for Transit Gateway deletion
  include_tasks: main_loop_transits.yml
  loop: "{{ peerings }}"

- name: Loop for VPCs deletion
  include_tasks: main_loop_vpcs.yml
  loop: "{{ vpcs | dict2items }}"
