---

- name: Find transit gateway {{ item.name }}
  community.aws.ec2_transit_gateway_info:
    region: "{{ item.region }}"
    filters:
      options.amazon-side-asn: "{{ item.asn }}"
  register: transit

# - name: Loop for Transit Attachments deletion
#   include_tasks: main_loop_attachments.yml
#   loop: "{{ item.attachments }}"

- debug:
    var: transit

- name: Delete transit gateway {{ item.name }}
  community.aws.ec2_transit_gateway:
    region: "{{ item.region }}"
    transit_gateway_id: '{{ transit.transit_gateways[0].transit_gateway_id }}'
    state: absent
  when: transit | length > 0
  ignore_errors: true

- name: Wait VPC peering connection to be deleted
  ansible.builtin.pause:
    seconds: 5
