---

- name: Delete Transit VPC attachments {{ item.vpc }}
  community.aws.ec2_transit_gateway_vpc_attachment:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    transit_gateway: "{{ transit.transit_gateway.transit_gateway_id }}"
    tags:
      Name: "{{ item.vpc }}"
    purge_subnets: false
    state: absent
  register: transit_attachment

- name: Wait VPC peering connection to be deleted
  ansible.builtin.pause:
    seconds: 5
