---

- debug: 
    var: transit

- name: Find Transit VPC attachment {{ item.vpc }}
  community.aws.ec2_transit_gateway_vpc_attachment:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    transit_gateway: "{{ transit.transit_gateways[0].transit_gateway_id }}"
    filters:
      "tag:Name": "{{ item.vpc }}"
  register: attachment

- debug: 
    var: attachment

- name: Delete Transit VPC attachment {{ item.vpc }}
  community.aws.ec2_transit_gateway_vpc_attachment:
    region: "{{ vpcs[item.vpc].ec2_vpc_region }}"
    transit_gateway: "{{ transit.transit_gateways[0].transit_gateway_id }}"
    id: "{{ attachment.attachments[0].attachment_id }}"
    state: absent
  ignore_errors: true

- name: Wait VPC peering connection to be deleted
  ansible.builtin.pause:
    seconds: 5
