---

- name: Loop for Peerings deletion
  include_tasks: main_loop_peerings.yml
  loop: "{{ peerings }}"

- name: Loop for VPCs deletion
  include_tasks: main_loop_vpcs.yml
  loop: "{{ vpcs | dict2items }}"
